In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df=pd.read_csv("/content/framingham.csv")

In [48]:
df.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [14]:
df.isnull().mean()*100

male               0.000000
age                0.000000
education          2.477584
currentSmoker      0.000000
cigsPerDay         0.684285
BPMeds             1.250590
prevalentStroke    0.000000
prevalentHyp       0.000000
diabetes           0.000000
totChol            1.179802
sysBP              0.000000
diaBP              0.000000
BMI                0.448325
heartRate          0.023596
glucose            9.155262
TenYearCHD         0.000000
dtype: float64

In [31]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer

In [32]:
columns=["education","cigsPerDay","totChol","BMI","heartRate","BPMeds"]
df=df.dropna(subset=columns,axis=0)

In [66]:
df.isnull().mean()*100

male               0.000000
age                0.000000
education          0.000000
currentSmoker      0.000000
cigsPerDay         0.000000
BPMeds             0.000000
prevalentStroke    0.000000
prevalentHyp       0.000000
diabetes           0.000000
totChol            0.000000
sysBP              0.000000
diaBP              0.000000
BMI                0.000000
heartRate          0.000000
glucose            8.301981
TenYearCHD         0.000000
dtype: float64

In [34]:
df.duplicated().sum()

np.int64(0)

In [80]:
from sklearn.model_selection import train_test_split,cross_val_score

In [64]:
X=df.drop("TenYearCHD",axis=1)
y=df["TenYearCHD"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [76]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)
imputer=SimpleImputer(strategy="mean")
X_train=imputer.fit_transform(X_train)
X_test=imputer.transform(X_test)
model=LogisticRegression()

In [77]:
model.fit(X_train,y_train)

LogisticRegression()

In [78]:
y_pred=model.predict(X_test)

In [79]:
from sklearn.metrics import recall_score

In [85]:
m=cross_val_score(model,X_train,y_train,cv=5,scoring="recall").mean()

In [86]:
m

np.float64(0.07083333333333335)